---
title: "baseline"
output: html_document
---

```{r}
library(tidyverse)
library(usmap)
library(gganimate)
library(gifski)
library(data.table)
library(scales)

options(scipen=999)
```

```{r}
NIH_grants <- read.csv("data/NIH_grants.csv", check.names = FALSE) %>%
  mutate(across(ends_with("Date"), ~ as_date(.x))) %>%
  filter(Type %in% c(1, 5))
```

```{r}
# vectors of historic funding in FY2025, proposed for FY2027
#FY2027 budget: https://www.whitehouse.gov/wp-content/uploads/2026/04/budget_fy2027.pdf
#historic budget for ICs and NIH: https://officeofbudget.od.nih.gov/pdfs/FY26/spending_hist/Mechanism%20Detail%20for%20Total%20NIH%20FY%202000%20-%20FY%202025%20(V).pdf
# unit is dollars in thousands
NIH_budg <- c(29211207+907010, 29964055+926485, 31316880+967125, 32602214+985017, 32495409+1001239, NA, NA, 29088661+932827)
inf_adj_budget <- NIH_budg *  inf_adj * 1000

NIH_cut <- 1- tail(inf_adj_budget, 1)/mean(head(inf_adj_budget, 5), na.rm=TRUE)

get_fisc <- function(date) {
  if_else(month(date) >= 10, year(date) + 1L, year(date))
}

fy_start <- function(fy) {
  as_date(paste0(fy - 1, "-10-01"))
}

ic_list <- c("NIAID", "NICHD", "NHLBI", "NCI", "OD", "NIDCR", "NINDS", "NIBIB", "NIGMS", 
             "NEI", "NIDA", "NIDDK", "NHGRI", "NIAAA", "NCATS", "NIEHS", "NIA", "NIMH",
             "NIAMS", "NLM", "NIMHD", "NIDCD", "NINR", "NCCIH", "FIC")

inf_adj <- c(1.77, 1.35, 1.33, 1.32, 1.31, 1.28, 1.25, 1.23, 1.21, 1.16, 1.07, 1.03, 1, 0.96)

inf_by_year <- tibble(inf = inf_adj, fisc_year = c(2001, 2013:2024, 2026))

budg_by_year <- NIH_grants %>%
  filter(`Funding IC(s)` %in% ic_list) %>%
  mutate(fisc_year = get_fisc(`Budget Start Date`)) %>%
  left_join(inf_by_year) %>%
  mutate(`Total Cost IC` = `Total Cost IC` * inf) %>%
  rename(award_id = `Application ID`,
         tot_cost = `Total Cost IC`,
         cost_idc = `Indirect Cost IC`,
         proj_num = `Project Number`,
         funding_ics = `Funding IC(s)`,
         budg_start = `Budget Start Date`,
         budg_end = `Budget End Date`,
         lat = Latitude,
         lon = Longitude,
         org_name = `Organization Name`) %>%
  filter(!is.na(budg_start) & !is.na(budg_end)) %>%
  select(org_name, lat, lon, proj_num, award_id, fisc_year, tot_cost, cost_idc, funding_ics, budg_start, budg_end) %>%
  filter(lat != 0 & lon != 0) %>%
  distinct() %>%
  arrange(budg_start) %>%
  rowwise() %>%  # split funding between years
  mutate(fy_seq = list(seq(fisc_year, get_fisc(budg_end)))) %>%
  unnest(fy_seq) %>%
  mutate(fisc_year = fy_seq,
         fisc_start = fy_start(fisc_year),
         fisc_end = fy_start(fisc_year + 1) - days(1),
         year_start = pmax(budg_start, fisc_start),
         year_end = pmin(budg_end, fisc_end)) %>%
  filter(fisc_year %in% 2020:2024) %>%
  rowwise() %>%
  mutate(week_start = list(
    seq(
      floor_date(
        year_start, 
        unit = "week", 
        week_start = if_else(wday(fisc_start) == 1, 7, wday(fisc_start) - 1)), 
      year_end, 
      by = "weeks")),
    num_weeks = length(week_start)) %>%
  unnest(week_start) %>%
  select(-c(fy_seq, fisc_end)) %>%
  mutate(week_end = week_start + days(6),
         budg_length = time_length(difftime(budg_end, budg_start, units = "days"), "weeks") + 1/7,
         # calculate proportion of week
         week_length = case_when(
           week_end - year_start <= days(6) ~ as.numeric((pmin(year_end, week_end) - year_start + 1)/7),
           year_end - week_start <= days(6) ~ as.numeric((year_end - pmax(year_start, week_start) + 1)/7),
           .default = 1),
         prop_award = week_length/budg_length,
         budg_per_week = prop_award * tot_cost)
```

```{r geo data}
state_mult_2026 <- read.csv("data/state_mult_2026.csv") %>% 
                rename(tot_fund = 2, 
                       econ_act = 8,
                       state_name= 1,
                       jobs_per_m = 3) %>%
                mutate(econ_act = as.numeric(gsub(",", "", econ_act)),
                       tot_fund = as.numeric(gsub(",", "", tot_fund)),
                       job_val = as.numeric(gsub(",", "", jobs_per_m))/1000000,
                       state_name = str_replace_all(state_name, "\\u00A0", " ")) %>%
                mutate(econ_mult = econ_act/tot_fund) %>%
                select(state_name, econ_mult, job_val) %>%
                left_join(data.frame(state_name = c(state.name, "District of Columbia"),
                                     state = c(state.abb, "DC"))) %>%
                select(-state_name) %>%
                filter(!is.na(state))

NIH_tract_fips <- read.csv("data/tract_dictionary.csv") %>%
  mutate(tractid = str_pad(tractid, 11, pad = "0"),
         FIPS = substr(tractid, 0, 5),
         lat = round(lat, 5),
         lon = round(lon, 5)) %>%
  filter(lat!=0 & !is.na(FIPS)) %>%
  select(org_name, tractid, FIPS, lat, lon) %>%
  distinct()

# I joined in the missing geoids from previous years to this
NIH_geoid <- read.csv("data/geoid_dictionary.csv") %>%
  mutate(GEOID = str_pad(GEOID, 4, pad = "0"),
         lat = round(lat, 5),
         lon = round(lon, 5)) %>%
  filter(lat!=0 & !is.na(GEOID))

NIH_state_fips <- read.csv("data/state_and_county_fips_master.csv") %>%
  mutate(FIPS = str_pad(FIPS, 5, pad = "0")) %>%
  left_join(state_mult_2026)

states <- tibble(
  state_name = c(state.name, "District of Columbia"),
  state = c(state.abb, "DC")) %>%
  left_join(
    NIH_state_fips %>%
      select(FIPS, state) %>%
      mutate(FIPS = str_sub(FIPS, 1, 2)) %>%
      distinct()) %>%
  arrange(state) %>%
  left_join(state_mult_2026)

write_csv(states, "data/states.csv")

# geoid_fips <- NIH_tract_fips %>%
#   left_join(NIH_geoid) %>%
#   left_join(NIH_state_fips) %>%
#   select(tractid, GEOID, name_geoid, state, FIPS)
```

```{r}
budg_by_year <- budg_by_year %>%
  mutate(lat = round(lat, 5),
         lon = round(lon, 5)) %>%
  left_join(NIH_tract_fips) %>%
  left_join(NIH_geoid) %>%
  mutate(tractid = ifelse(tractid == "00NOT_FOUND", NA, tractid)) %>%
  filter(!is.na(tractid))

start_date <- as_date("2023-10-01")
end_date <- as_date("2024-09-30")

dates <- data.frame(
  week_start = seq(start_date, end_date, by = "weeks"),
  week = seq(1, 53, by = 1)
) %>%
  mutate(week_start = format(week_start, "%m-%d"))

budg_by_year <- budg_by_year %>%
  mutate(week_start = 
           if_else(fisc_year %% 4 != 0, 
                   if_else(month(week_start) >= 3 & month(week_start) <= 9, 
                           week_start - days(1), 
                           week_start), 
                   week_start),
         week_start = format(week_start, "%m-%d")) %>%
  left_join(dates)

# adding in IC filtering
budg_by_year_sum_fips <- budg_by_year %>%
  group_by(tractid, fisc_year, week_start, week) %>%
  summarise(week_sum = sum(budg_per_week)) %>%
  ungroup() %>%
  complete(tractid, fisc_year, week = seq(1, 53, by = 1),
           fill = list(week_sum = 0)) %>%
  select(-week_start) %>%
  left_join(dates) %>%
  group_by(tractid, fisc_year) %>%
  arrange(week) %>%
  mutate(ytd = cumsum(week_sum)) %>%
  group_by(tractid, week_start, week) %>%
  summarise(avg_ytd = mean(ytd))

budg_by_year_sum_fips %>%
  group_by(week) %>%
  summarize(avg_ytd = sum(avg_ytd)) %>%
  ggplot(aes(x = week, y = avg_ytd)) +
  geom_line() +
  scale_y_continuous(labels = label_dollar(scale_cut = cut_short_scale()),
                     limits = c(0, NA))

budg_by_year %>%
  group_by(tractid, fisc_year, week_start, week) %>%
  summarise(week_sum = sum(budg_per_week)) %>%
  ungroup() %>%
  complete(tractid, fisc_year, week = seq(1, 53, by = 1),
           fill = list(week_sum = 0)) %>%
  group_by(week, fisc_year) %>%
  summarise(week_sum = sum(week_sum)) %>%
  group_by(week) %>%
  summarize(week_avg = mean(week_sum)) %>%
  ggplot(aes(x = week, y = week_avg)) +
  geom_line() +
  scale_y_continuous(labels = label_dollar(scale_cut = cut_short_scale()),
                     limits = c(0, NA))

budg_by_year %>%
  mutate(day_fisc = time_length(year_start - fisc_start, unit = "days") + 1,
         week = ceiling(day_fisc/7)) %>%
  group_by(tractid, fisc_year, week) %>%
  summarise(week_sum = sum(budg_per_week)) %>%
  ungroup() %>%
  complete(tractid, fisc_year, week = seq(1, 53, by = 1),
           fill = list(week_sum = 0)) %>%
  group_by(tractid, fisc_year) %>%
  mutate(ytd = cumsum(week_sum)) %>%
  group_by(fisc_year, week) %>%
  summarise(ytd = sum(ytd)) %>%
  group_by(fisc_year) %>%
  ggplot(aes(x = week, y = ytd, group = fisc_year, color = fisc_year)) +
  geom_line() +
  ylim(0, NA)
```

```{r}
county_commute <- read.csv("data/county_commute_NIH.csv") %>%
  select(DESTINATION, DESTINATION_total_workers, Commuters, ORIGIN, proportion) %>% 
  mutate(DESTINATION = str_pad(DESTINATION, 11, pad = "0"),
         ORIGIN = str_pad(ORIGIN, 5, pad = "0"))

cong_commute <- fread("https://osf.io/m5kb6/download") %>%
  mutate(Cong_DESTINATION = str_pad(w_tract, 11, pad = "0"),
         Cong_ORIGIN = str_pad(h_cd119, 4, pad = "0")) %>%
  rename(commuters = commutes) %>%
  filter(!is.na(Cong_ORIGIN))

cong_info <- read.csv("./data/us_representatives_119th_congress.csv") %>%
  mutate(GEOID = str_pad(GEOID, 4, pad = "0")) %>%
  select(GEOID, STATE_NAME, NAME, PARTY) %>%
  rename(state = STATE_NAME,
         pol_party = PARTY,
         rep_name = NAME)

#get total workers per cong district
cong_commute_sum <- cong_commute %>%
  group_by(Cong_DESTINATION) %>%
  summarise(total_workers = sum(commuters, na.rm=TRUE))

#merge in total workers
cong_commute <- left_join(cong_commute, cong_commute_sum) %>%
  select(Cong_DESTINATION, Cong_ORIGIN, commuters, total_workers) %>%
  rename(DESTINATION = Cong_DESTINATION,
         ORIGIN = Cong_ORIGIN)

#calculate proportion of workers who work in district X who live in district Y
cong_commute$proportion <- cong_commute$commuters / cong_commute$total_workers
```

```{r}
# tract to county commutes
commuter_dist <- function(week_num){
  data <- budg_by_year_sum_fips %>% filter(week == week_num)
  
  baseline_ic <- county_commute %>%
  rename(tractid = DESTINATION) %>%
  right_join(data) %>%
  mutate(avg_ytd = avg_ytd * proportion) %>%
  group_by(ORIGIN, week, week_start) %>%
  summarize(avg_ytd = sum(avg_ytd)) %>%
  rename(FIPS = ORIGIN) %>%
  filter(!endsWith(FIPS, "000"))
  
  baseline_ic
}

budg_by_year_sum_comm_ic <- lapply(1:53, commuter_dist)
budg_by_year_sum_comm_ic <- do.call(rbind, budg_by_year_sum_comm_ic)


budg_by_year_sum_comm_ic <- budg_by_year_sum_comm_ic %>%
  mutate(state_FIPS = str_sub(FIPS, 1, 2)) %>%
  left_join(states %>% rename(state_FIPS = FIPS)) %>%
  left_join(NIH_state_fips %>% select(FIPS, name)) %>%
  mutate(econ_ytd = avg_ytd * econ_mult,
         jobs = avg_ytd * job_val,
         funding_ics = "NIH_tot") %>%
  select(-c(econ_mult, job_val, state_FIPS, state_name))

msa <- read.csv("data/cbsa2fipsxw_2023.csv") %>%
  select(CountyFIPS, CBSA_NAME, CBSA_FIPS) %>%
  rename(FIPS = CountyFIPS) %>%
  mutate(FIPS = str_pad(FIPS, 5, pad ="0"),
         CBSA_FIPS = str_pad(CBSA_FIPS, 5, pad ="0"))

# baseline funding data frames
baseline_timevar <- budg_by_year_sum_comm_ic %>%
  select(FIPS, name, state, funding_ics, week, week_start, avg_ytd, econ_ytd, jobs)

write_csv(baseline_timevar, "output/baseline_timevar.csv")

county_pop <- read.csv("data/county_pop.csv") %>%
  mutate(FIPS = str_pad(FIPS, 5, pad = "0"))

state_pop <- read.csv("data/state_pop.csv") %>%
  mutate(across(c(pop_2024, pop_2025), ~ as.numeric(str_remove_all(.x, ",")))) %>%
  mutate(state_name = str_remove_all(state, "\\.")) %>%
  left_join(states) %>%
  select(state, pop_2024)

city_pop <- read.csv("data/city_pop_2024.csv", skip = 1) %>%
  mutate(area_type = str_extract(MSA, "\\b\\w+\\s+\\w+$"),
         MSA = str_remove(MSA, "\\s*\\b\\w+\\s+\\w+$"),
         MSA = str_remove_all(MSA, "^\\.+"),
         pop_2024 = as.numeric(str_remove_all(pop_2024, ","))) %>%
  rename(CBSA_NAME = MSA)

baseline_tot <- baseline_timevar %>%
  filter(week == 53) %>%
  ungroup() %>%
  select(-c(week, week_start)) %>%
  rename(raw_funding = avg_ytd,
         econ_impact = econ_ytd) %>%
  left_join(county_pop %>% select(FIPS, pop_2024))

write_csv(baseline_tot, "output/baseline_county.csv")

baseline_tot %>%
    select(-pop_2024) %>%
    right_join(msa) %>%
    group_by(CBSA_FIPS, CBSA_NAME, funding_ics) %>%
    summarize(
        raw_funding = sum(raw_funding),
        econ_impact = sum(econ_impact),
        jobs = sum(jobs)) %>%
  left_join(city_pop) %>% 
  select(-area_type) %>%
  write_csv("output/baseline_city.csv")

```

```{r tract to congressional district}
budg_by_year_geoid <- budg_by_year_sum_fips %>% 
  filter(week == 53) %>% 
  distinct() %>%
  select(-c(week, week_start))

baseline_geoid <- cong_commute %>%
  rename(tractid = DESTINATION) %>%
  right_join(budg_by_year_geoid) %>%
  mutate(avg_ytd = avg_ytd * proportion) %>%
  group_by(ORIGIN) %>%
  summarize(raw_funding = sum(avg_ytd)) %>%
  rename(GEOID = ORIGIN)

baseline_geoid <- baseline_geoid %>%
  left_join(cong_info %>% select(GEOID, state) %>% rename(state_name = state)) %>%
  left_join(states) %>%
  mutate(econ_impact = raw_funding * econ_mult,
         jobs = raw_funding * job_val,
         funding_ics = "NIH_tot") %>%
  select(-c(state_name, FIPS, econ_mult, job_val)) %>%
  distinct()

geoid_pop <- read.csv("data/CD_pop2024.csv") %>%
  mutate(state = sub(" [^ ]+$", "", District),
         dist_num = as.numeric(sub(".*\\s+", "", District)),
         pop_2024 = as.numeric(gsub(",", "", Population))) %>%
  mutate(dist_num = ifelse(is.na(dist_num), 0, dist_num)) %>%
  # manually set DC
  mutate(dist_num = ifelse(state == "District of Columbia", 98, dist_num)) %>%
  # append state FIPS
  right_join(cong_info %>% 
               mutate(state_GEOID = substr(GEOID, 1, 2)) %>% 
               select(state_GEOID, state) %>% 
               distinct()) %>%
  mutate(dist_num = str_pad(dist_num, 2, pad = "0")) %>%
  mutate(GEOID = paste0(state_GEOID, dist_num)) %>%
  select(GEOID, pop_2024) %>%
  distinct()

baseline_geoid %>%
  select(GEOID, state, funding_ics, raw_funding, econ_impact, jobs) %>%
  left_join(geoid_pop) %>%
  write_csv("output/baseline_district.csv")

baseline_geoid %>%
  group_by(state, funding_ics) %>%
  summarize(
    raw_funding = sum(raw_funding),
    econ_impact = sum(econ_impact),
    jobs = sum(jobs)) %>%
  left_join(state_pop) %>%
  filter(!is.na(state)) %>%
  write_csv("output/baseline_state.csv")
```

```{r test values}
budg_by_year_sum_comm_ic %>%
  filter(week == 53) %>%
  ungroup() %>%
  summarize(total_funding = sum(avg_ytd))

baseline_tot %>%
  ungroup() %>%
  summarize(total_funding = sum(raw_funding))

budg_by_year %>%
  group_by(fisc_year) %>%
  summarise(total_funding = sum(budg_per_week, na.rm = TRUE))

sum(budg_by_year$budg_per_week, na.rm = TRUE)/5

budg_by_year_sum_fips %>%
  filter(week == 53) %>%
  ungroup() %>%
  summarize(total_funding = sum(avg_ytd))

baseline_geoid %>%
  ungroup() %>%
  summarize(total_funding = sum(raw_funding))
```

