---
title: "NIH_terminations"
output: html_document
---

```{r}
library(tidyverse)
library(data.table)
```

```{r}
terminations_raw <- read_csv("https://files.grant-witness.us/nih_v3_terminations.csv") %>%
  mutate(across(ends_with("date"), ~ as_date(.x))) %>%
  mutate(Type = as.numeric(str_sub(full_award_number, 1, 1)))

write.csv(terminations_raw, "data/nih_v3_terminations.csv")
```

```{r fix org names}
# some blanket fixes on org name
org_names_corrected <- read.csv("data/org_names_corrected.csv") %>%
  filter(!is.na(corrected_name) & corrected_name != "")

replacements <- c(" Of " = " of ", "At" = "at", " And " = " and ",
                  "Univ " = "University ", "Ctr" = "Center", 
                  "Col " = "College ", "Hlth" = "Health", "Scis" = "Sciences",
                  "Sci " = "Science ", "Llc" = "LLC", "Assn" = "Association",
                  " The " = " the ", " For " = " for ", "Res " = "Research ", 
                  "Hosp " = "Hospital ", "Med " = "Medical ",
                  " Inst " = " Institute ", " Can " = " Cancer ")

NIH_tracts <- read.csv("data/tract_dictionary.csv") %>%
  mutate(tractid = str_pad(tractid, 11, pad = "0"),
         FIPS = str_pad(FIPS, 5, pad = "0"))

states <- read.csv("data/states.csv") %>%
  mutate(state_FIPS = str_pad(state_FIPS, 2, pad = "0"))

names_v3 <- read.csv("data/org_names_v3_terminations.csv")

terminations_raw <- terminations_raw %>%
  mutate(org_name = if_else(org_name == "UNIVERSITY OF COLORADO", str_to_upper(paste(org_name, org_city, sep = " - ")), org_name))

terminations_clean <- terminations_raw %>%
  filter(!is.na(org_state)) %>%
  filter(!org_state %in% c("ON", "BC")) %>%
  filter(org_country == "UNITED STATES") %>%
  group_by(grant_id) %>%
  filter(is.na(subgrant_id) | !any(is.na(subgrant_id))) %>% # filter out subgrants unless no parent award is present
  ungroup() %>%
  left_join(states %>% 
              rename(org_state = state_name) %>% 
              mutate(org_state = str_to_upper(org_state)) %>%
              select(state, org_state)) %>%
  mutate(org_state = if_else(!is.na(state), state, org_state)) %>%
  select(-state) %>%
  left_join(states %>% rename(org_state = state)) %>%
  left_join(names_v3) %>%
  mutate(org_name = if_else(!is.na(org_name_fixed), org_name_fixed, org_name)) %>%
  select(-org_name_fixed) %>%
  left_join(NIH_tracts) %>%
  mutate(org_name = str_to_title(org_name),
         org_city = str_to_title(org_city),
         org_name = str_replace_all(org_name, replacements)) %>%
  left_join(org_names_corrected) %>%
  mutate(org_name = if_else(!is.na(corrected_name), corrected_name, org_name)) %>%
  select(-corrected_name)

# terminated grants in the US since 2/28/25
start_date <- as_date("2025-02-28")
```

```{r}
terminations <- terminations_clean %>%
  mutate(current_loss = if_else(obligated_at_disruption >= spent_at_disruption, obligated_at_disruption - spent_at_disruption, 0),
         across(ends_with("loss"), ~ if_else(is.na(.x), 0, .x)),
         earliest_date_impacted = pmin(first_termination_date, frozen_date, na.rm = T),
         latest_date_impacted = pmax(latest_termination_date, frozen_date, na.rm = T),
         date_reinstated = pmax(latest_reinstatement_date, unfrozen_date, na.rm = T),
         date_reinstated = if_else(date_reinstated < latest_date_impacted, NA, date_reinstated),
         tractid = if_else(tractid == "00NOT_FOUND", NA, tractid)) %>%
  filter(!is.na(tractid)) %>%
  filter(earliest_date_impacted >= start_date)

nrow(terminations)

terminations <- terminations %>%
  # reinstated grants are counted as negative loss
  pivot_longer(c(earliest_date_impacted, latest_date_impacted, date_reinstated), names_to = "date_status", values_to = "date") %>% 
  filter(!is.na(date)) %>%
  mutate(overall_loss = if_else(date_status == "earliest_date_impacted", current_loss, 0), # total amount ever impacted
         current_loss = 
           case_when(
             date_status == "date_reinstated" ~ -current_loss,
             date_status == "latest_date_impacted" ~ current_loss,
             date_status == "earliest_date_impacted" ~  0), # total amount lost at the moment
         overall_grant_loss = if_else(date_status == "earliest_date_impacted", 1, 0),
         current_grant_loss = case_when(
             date_status == "date_reinstated" ~ -1,
             date_status == "latest_date_impacted" ~ 1,
             date_status == "earliest_date_impacted" ~  0),
         week = floor_date(date, unit = "week", week = if_else(wday(start_date) == 1, 7, wday(start_date) - 1)))

org_dict <- read.csv("data/org_dict.csv") %>%
  mutate(across(c(starts_with("lat"), starts_with("lon")), ~ round(.x, 5)))

terminations <- terminations %>%
  rename_with(~ paste0(.x, ".nih", recycle0 = TRUE), c("org_name", "org_state", "org_city", "lat", "lon")) %>%
  left_join(org_dict %>% select(-ends_with(".nsf"), -c(lat.nih, lon.nih)) %>% distinct()) %>% 
  mutate(org_name = if_else(is.na(org_name), org_name.nih, org_name),
         org_city = if_else(is.na(org_city), org_city.nih, org_city),
         org_state = if_else(is.na(org_state), org_state.nih, org_state),
         lat = if_else(is.na(lat), lat.nih, lat),
         lon = if_else(is.na(lon), lon.nih, lon)) %>%
  select(-ends_with(".nih"), ends_with(".nsf"))

# organization level
terminations_org <- terminations %>%
  complete(nesting(org_name, org_city, org_state, lat, lon), 
           week = seq(start_date, today(), by = "weeks"),
           fill = list(current_loss = 0, overall_loss = 0, current_grant_loss = 0, overall_grant_loss = 0)) %>%
  group_by(org_name, org_city, org_state, lat, lon, week) %>%
  summarize(across(c(current_loss, overall_loss, current_grant_loss, overall_grant_loss), ~ sum(.x))) %>%
  group_by(org_name, org_city, org_state, lat, lon) %>%
  arrange(week) %>%
  mutate(across(c(current_loss, overall_loss, current_grant_loss, overall_grant_loss), ~ cumsum(.x))) %>%
  left_join(states %>% rename(org_state = state)) %>%
  mutate(current_econ_loss = current_loss * econ_mult,
         current_job_loss = current_loss * job_val,
         overall_econ_loss = overall_loss * econ_mult,
         overall_job_loss = overall_loss * job_val) %>%
  select(org_name, org_city, org_state, lat, lon, starts_with(c("week", "current", "overall")))

write_csv(terminations_org, "output/terminations_org.csv")

terminations_sum <- terminations %>%
  group_by(tractid, week) %>%
  summarise(week_loss = sum(current_loss),
            week_impacted = sum(overall_loss))
```

```{r commutes}
county_commute <- fread("data/county_commute_NIH.csv") %>%
  select(DESTINATION, DESTINATION_total_workers, Commuters, ORIGIN, proportion) %>% 
  mutate(DESTINATION = str_pad(DESTINATION, 11, pad = "0"),
         ORIGIN = str_pad(ORIGIN, 5, pad = "0"))

county_commute_territory <- terminations %>%
  filter(as.numeric(str_sub(FIPS, 1, 2)) > 56) %>%
  rename(DESTINATION = tractid,
         ORIGIN = FIPS) %>%
  mutate(DESTINATION_total_workers = 0,
         Commuters = 0,
         proportion = 1) %>%
  ungroup() %>%
  select(DESTINATION, DESTINATION_total_workers, Commuters, ORIGIN, proportion) %>%
  distinct()

county_commute <- county_commute %>%
  filter(ORIGIN != "00000") %>%
  rbind(county_commute_territory)

# Quality check: all destination weights should sum to 1
county_commute %>% 
  group_by(DESTINATION) %>% 
  summarize(sum = round(sum(proportion), digits=5)) %>% 
  filter(sum < 1) %>%
  nrow() 


# district level
cong_commute <- fread("https://osf.io/m5kb6/download") %>%
  mutate(Cong_DESTINATION = str_pad(w_tract, 11, pad = "0"),
         Cong_ORIGIN = str_pad(h_cd119, 4, pad = "0")) %>%
  rename(commuters = commutes) %>%
  filter(!is.na(Cong_ORIGIN))

cong_commute_territory <- terminations %>%
  filter(as.numeric(str_sub(FIPS, 1, 2)) > 56) %>%
  rename(DESTINATION = tractid) %>%
  mutate(ORIGIN = paste0(str_sub(DESTINATION, 1, 2), "98"),
         total_workers = 0,
         commuters = 0,
         proportion = 1) %>%
  ungroup() %>%
  select(DESTINATION, total_workers, commuters, ORIGIN, proportion) %>%
  distinct()

cong_info <- read.csv("./data/us_representatives_119th_congress.csv") %>%
  mutate(GEOID = str_pad(GEOID, 4, pad = "0")) %>%
  select(GEOID, STATE_NAME, NAME, PARTY) %>%
  rename(state = STATE_NAME,
         pol_party = PARTY,
         rep_name = NAME)

# get total workers per cong district
cong_commute_sum <- cong_commute %>%
  group_by(Cong_DESTINATION) %>%
  summarise(total_workers = sum(commuters, na.rm=TRUE))

# merge in total workers
cong_commute <- left_join(cong_commute, cong_commute_sum) %>%
  select(Cong_DESTINATION, Cong_ORIGIN, commuters, total_workers) %>%
  rename(DESTINATION = Cong_DESTINATION,
         ORIGIN = Cong_ORIGIN)

# calculate proportion of workers who work in district X who live in district Y
cong_commute$proportion <- cong_commute$commuters / cong_commute$total_workers

cong_commute <- cong_commute %>%
  add_row(DESTINATION = "30005940100", ORIGIN = "3002", commuters = 0, total_workers = 0, proportion = 1) %>%
  bind_rows(cong_commute_territory)
```

```{r}
# add in commutes
terminations_sum_comm <- county_commute %>%
  rename(tractid = DESTINATION) %>%
  right_join(terminations_sum) %>%
  mutate(week_loss = week_loss * proportion,
         week_impacted = week_impacted * proportion) %>%
  group_by(ORIGIN, week) %>%
  summarize(week_loss = sum(week_loss),
            week_impacted = sum(week_impacted)) %>%
  rename(FIPS = ORIGIN) %>%
  filter(!endsWith(FIPS, "000")) %>%
  ungroup() %>%
  complete(FIPS, week = seq(start_date, today(), by = "weeks"),
           fill = list(week_loss = 0, week_impacted = 0)) %>%
  group_by(FIPS) %>%
  arrange(week) %>%
  mutate(current_loss = cumsum(week_loss),
         overall_loss = cumsum(week_impacted))

# add in state multipliers
terminations_sum_comm <- terminations_sum_comm %>%
  mutate(state_FIPS = str_sub(FIPS, 1, 2)) %>%
  left_join(states) %>%
  mutate(current_econ_loss = current_loss * econ_mult,
         current_job_loss = current_loss * job_val,
         overall_econ_loss = overall_loss * econ_mult,
         overall_job_loss = overall_loss * job_val) %>%
  select(FIPS, week, starts_with(c("current", "overall")))

write_csv(terminations_sum_comm, "output/terminations_county.csv")

msa <- read.csv("data/cbsa2fipsxw_2023.csv") %>%
  select(CountyFIPS, CBSA_NAME, CBSA_FIPS) %>%
  rename(FIPS = CountyFIPS) %>%
  mutate(FIPS = str_pad(FIPS, 5, pad ="0"),
         CBSA_FIPS = str_pad(CBSA_FIPS, 5, pad ="0"))

fips_names <- read.csv("data/state_and_county_fips_master.csv") %>%
  mutate(FIPS = str_pad(FIPS, 5, pad ="0")) %>%
  select(FIPS, name)

terminations_sum_comm %>%
  left_join(msa) %>%
  left_join(fips_names) %>%
  mutate(CBSA_FIPS = if_else(is.na(CBSA_FIPS), FIPS, CBSA_FIPS)) %>%
  mutate(CBSA_NAME = if_else(is.na(CBSA_NAME), name, CBSA_NAME)) %>%
  group_by(CBSA_FIPS, CBSA_NAME, week) %>%
  summarise(across(ends_with("loss"), ~ sum(.x))) %>%
  write_csv("output/terminations_city.csv")

# congressional district
terminations_sum_cong <- cong_commute %>%
  rename(tractid = DESTINATION) %>%
  right_join(terminations_sum) %>%
  mutate(week_loss = week_loss * proportion,
         week_impacted = week_impacted * proportion) %>%
  group_by(ORIGIN, week) %>%
  summarize(week_loss = sum(week_loss),
            week_impacted = sum(week_impacted)) %>%
  rename(GEOID = ORIGIN) %>%
  ungroup() %>%
  complete(GEOID, week = seq(start_date, today(), by = "weeks"),
           fill = list(week_loss = 0, week_impacted = 0)) %>%
  group_by(GEOID) %>%
  arrange(week) %>%
  mutate(current_loss = cumsum(week_loss),
         overall_loss = cumsum(week_impacted))

terminations_sum_cong <- terminations_sum_cong %>%
  mutate(state_FIPS = str_sub(GEOID, 1, 2)) %>%
  left_join(states) %>%
  mutate(current_econ_loss = current_loss * econ_mult,
         current_job_loss = current_loss * job_val,
         overall_econ_loss = overall_loss * econ_mult,
         overall_job_loss = overall_loss * job_val) %>%
  select(GEOID, state, week, starts_with(c("current", "overall")))

write_csv(terminations_sum_cong %>% select(-state), "output/terminations_district.csv")

terminations_sum_cong %>%
  group_by(state, week) %>%
  summarise(across(ends_with("loss"), ~ sum(.x))) %>%
  write_csv("output/terminations_state.csv")
```

```{r check values}
# check to see if values line up
terminations_sum_comm %>% 
    filter(week == max(week)) %>%
  ungroup() %>%
  summarize(overall_loss = sum(overall_loss), current_loss = sum(current_loss))

terminations_sum_cong %>% 
    filter(week == max(week)) %>%
  ungroup() %>%
  summarize(overall_loss = sum(overall_loss),
            current_loss = sum(current_loss))

# pre-commuter flows
terminations %>%
  ungroup() %>%
  summarize(overall_loss = sum(overall_loss), current_loss = sum(current_loss))
```

```{r eval=FALSE}
library(gganimate)
library(gifski)
library(usmap)
library(scales)

# weekly version
gif_map_week <- plot_usmap(
  data = terminations_sum_comm %>% rename(fips = FIPS) %>% mutate(current_loss = current_loss + 1),
  values = "current_loss",
  regions = "counties",
  color = "white",
  linewidth = 0.0
) +
  scale_fill_viridis_c(trans = "log10",
                       labels = label_dollar(scale_cut = cut_short_scale())) +
  labs(fill = "Current funding \nimpacted", title = "{frame_time}") +
  theme(legend.position = "right")+
  transition_time(week) +
  ease_aes("linear")

anim_save("output/current_terminations_weekly.gif", animate(gif_map_week, fps = 5, renderer = gifski_renderer()))
```

