---
title: "NSF_terminations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require('rstudioapi')) BiocManager::install("rstudioapi");library(rstudioapi)

# change working directory to folder with script
setwd(dirname(rstudioapi::getSourceEditorContext()$path)) 

library(tidyverse)
library(readxl)
library(sf)
library(data.table)
library(magrittr)

options(scipen=999)
```

```{r}
nsf_terminations <- read_csv("https://files.grant-witness.us/nsf_terminations.csv") %>%
  mutate(across(ends_with("date"), ~ as_date(.x)))

write.csv(nsf_terminations, "data/nsf_terminations.csv")

# read in grant data
nsf_grants <- read.csv("nsf_data/nsf_grants.csv")

states <- read.csv("data/states.csv") %>%
  mutate(state_FIPS = str_pad(FIPS, 2, pad = "0")) %>%
  select(-FIPS)

state_dict_territories <- read.csv("data/state_dict_territories.csv") %>%
  mutate(FIPS = as.character(FIPS),
         state_FIPS = as.character(state_FIPS)) %>%
  select(names(states)) %>%
  distinct()

states <- rbind(states, state_dict_territories) %>%
  arrange(state)

orgs <- nsf_grants %>% 
  distinct(inst_name, inst_city_name, inst_state_name, inst_street_address) %>% 
  rename(org_name = inst_name, 
         org_city = inst_city_name, 
         state_name = inst_state_name) %>% 
  left_join(states %>% rename(org_state = state)) %>% 
  mutate(org_name = if_else(org_name == "Carnegie-Mellon University", "Carnegie Mellon University", org_name),
         org_name = if_else(org_name == "Manhattan College", "MANHATTAN UNIVERSITY", org_name),
         org_name = if_else(org_name == "OHIO STATE UNIVERSITY, THE", "Ohio State University", org_name),
         org_city = if_else(org_name == "Arizona State University", "TEMPE", org_city),
         inst_street_address = if_else(org_name == "University of Miami", "1251 MEMORIAL DR", inst_street_address)) %>%
  select(-c(state_name)) %>%
  distinct() %>%
  mutate(org_city = str_to_upper(org_city))

nsf_terminations <- nsf_terminations %>%
  mutate(org_name = if_else(org_name == "OHIO STATE UNIVERSITY, THE", "Ohio State University", org_name),
         org_name = if_else(org_name == "University of Colorado Boulder", "University of Colorado at Boulder", org_name),
         org_city = if_else(org_name == "Knology Ltd.", "NEW YORK", org_city),
         org_state = if_else(org_name == "Knology Ltd.", "New York", org_state),
         org_city = if_else(org_name == "University of Colorado at Boulder", "BOULDER", org_city),
         org_city = if_else(org_name == "Arizona State University", "TEMPE", org_city),
         org_city = str_to_upper(org_city)) %>%
  left_join(orgs) %>% 
  filter(org_state %in% c(state.abb, "DC", "AS", "GU", "MP", "PR", "VI"))

#directorates to include
dir_incl <- c("BIO", "CSE", "EDU", "ENG", "GEO", "MPS", "SBE", "TIP")

# divisions within office of director to include
div_incl <- c("OIA", "OISE")

# helper column to put listed account categories together (O/D divisions are split out)
nsf_terminations %<>% mutate(account_name = ifelse(dir == "O/D", div, dir)) %>%
  filter(account_name %in% c(dir_incl, div_incl))

# get tracts
geo_dict <- read.csv("nsf_data/NSF_addresses_US_tract_county_cong119.csv") %>%
  distinct() %>%
  mutate(FIPS = str_pad(CountyFIPS_str, 5, pad = "0"),
         GEOID = str_pad(CongFIPS, 4, pad="0"),
         tractid = str_pad(TractFIPS_Str, 11, pad="0"),
         inst_street_address = inst_stree) %>%
  rename(lat = Lat, lon = Lon) %>%
  select(tractid, inst_street_address, inst_name, lat, lon) %>%
  distinct() %>%
  rename(org_name = inst_name) %>% 
  mutate(org_name = if_else(org_name == "Carnegie-Mellon University", "Carnegie Mellon University", org_name),
         org_name = if_else(org_name == "Manhattan College", "MANHATTAN UNIVERSITY", org_name))

missing_tractid_orgs <- read.csv("data/missing_tractid_org_fixed.csv") %>%
  mutate(GEOID = str_pad(GEOID, 11, pad = "0")) %>%
  rename(tractid = GEOID,
         org_name = inst_name) %>%
  select(tractid, inst_street_address, org_name, lat, lon) %>%
  distinct()

geo_dict <- rbind(geo_dict, missing_tractid_orgs)

nsf_terminations %<>% left_join(geo_dict)

nsf_terminations %>% filter(is.na(tractid))
```

```{r}
county_commute <- read.csv("data/county_commute_NIH.csv") %>%
  select(DESTINATION, DESTINATION_total_workers, Commuters, ORIGIN, proportion) %>% 
  mutate(DESTINATION = str_pad(DESTINATION, 11, pad = "0"),
         ORIGIN = str_pad(ORIGIN, 5, pad = "0")) %>%
  add_row(DESTINATION = "30005940100", DESTINATION_total_workers = 0, Commuters = 0, ORIGIN = "30005", proportion = 1)

county_commute_territory <- nsf_terminations %>%
  filter(as.numeric(str_sub(tractid, 1, 2)) > 56) %>%
  mutate(ORIGIN = str_sub(tractid, 1, 5)) %>%
  rename(DESTINATION = tractid) %>%
  mutate(DESTINATION_total_workers = 0,
         Commuters = 0,
         proportion = 1) %>%
  ungroup() %>%
  distinct(DESTINATION, DESTINATION_total_workers, Commuters, ORIGIN, proportion)

county_commute <- county_commute %>%
  filter(as.numeric(str_sub(DESTINATION, 1, 2)) <= 56) %>%
  rbind(county_commute_territory)

cong_commute <- fread("https://osf.io/m5kb6/download") %>%
  mutate(Cong_DESTINATION = str_pad(w_tract, 11, pad = "0"),
         Cong_ORIGIN = str_pad(h_cd119, 4, pad = "0")) %>%
  rename(commuters = commutes) %>%
  filter(!is.na(Cong_ORIGIN))

cong_commute_territory <- county_commute_territory %>%
  mutate(ORIGIN = paste0(str_sub(ORIGIN, 1, 2), "98")) %>%
  rename(total_workers = DESTINATION_total_workers,
         commuters = Commuters) %>%
  distinct()

cong_info <- read.csv("./data/us_representatives_119th_congress.csv") %>%
  mutate(GEOID = str_pad(GEOID, 4, pad = "0")) %>%
  select(GEOID, STATE_NAME, NAME, PARTY) %>%
  rename(state = STATE_NAME,
         pol_party = PARTY,
         rep_name = NAME)

# get total workers per cong district
cong_commute_sum <- cong_commute %>%
  group_by(Cong_DESTINATION) %>%
  summarise(total_workers = sum(commuters, na.rm=TRUE))

# merge in total workers
cong_commute <- left_join(cong_commute, cong_commute_sum) %>%
  select(Cong_DESTINATION, Cong_ORIGIN, commuters, total_workers) %>%
  rename(DESTINATION = Cong_DESTINATION,
         ORIGIN = Cong_ORIGIN)

# calculate proportion of workers who work in district X who live in district Y
cong_commute$proportion <- cong_commute$commuters / cong_commute$total_workers

cong_commute <- cong_commute %>%
  add_row(DESTINATION = "30005940100", ORIGIN = "3002", commuters = 0, total_workers = 0, proportion = 1) %>%
  bind_rows(cong_commute_territory)
```

```{r}
start_date <- as_date("2025-02-28")

# number of terminated grants NSF
nsf_terminations %>%
  filter(termination_date >= start_date) %>%
  nrow()

nsf_terminations %<>%
  filter(termination_date >= start_date) %>%
  pivot_longer(c(termination_date, reinstatement_date), names_to = "date_status", values_to = "date") %>% 
  filter(!is.na(date)) %>%
  mutate(total_loss = estimated_budget - estimated_outlays,
         total_loss = if_else(total_loss < 0, 0, total_loss), 
         total_loss = if_else(date_status == "reinstatement_date", -total_loss, total_loss), # total amount lost at the moment
         total_impacted = if_else(total_loss < 0, 0, total_loss), # total amount ever impacted
         grant_loss = if_else(date_status == "termination_date", 1, -1),
         grants_impacted = if_else(grant_loss < 0, 0, grant_loss),
         week = floor_date(date, 
                           unit = "week", 
                           week_start = if_else(wday(start_date) == 1, 7, wday(start_date) - 1)))

nsf_econ_mult <- 2.64
nsf_job_val <- 1/72000

replacements <- c(" Of " = " of ", " At " = " at ", " And " = " and ", " In " = " in ",
                  "Univ " = "University ", "Ctr" = "Center", " Inc$" = " Inc.",
                  "Col " = "College ", "Hlth" = "Health", "Scis" = "Sciences",
                  "Sci " = "Science ", "Llc" = "LLC", "Assn" = "Association",
                  " The " = " the ", " For " = " for ", "Res " = "Research ", 
                  "Hosp " = "Hospital ", "Med " = "Medical ", " Inst " = " Institute ", 
                  " Can " = " Cancer ", "Cuny" = "CUNY", "Suny" = "SUNY")

names_corrected <- read.csv("data/nsf_names_corrected.csv")

nsf_terminations_clean <- nsf_terminations %>%
  mutate(org_name = str_to_title(org_name),
         org_city = str_to_title(org_city),
         org_name = str_replace_all(org_name, replacements)) %>%
  left_join(names_corrected) %>%
  mutate(org_name = if_else(!is.na(corrected_name), corrected_name, org_name),
         lat = round(lat, 5),
         lon = round(lon, 5))

org_dict <- read.csv("data/org_dict.csv") %>%
  mutate(org_name.nsf = str_replace_all(org_name.nsf, replacements)) %>%
  left_join(names_corrected %>% rename(org_name.nsf = org_name)) %>%
  mutate(org_name.nsf = if_else(!is.na(corrected_name), corrected_name, org_name.nsf),
         across(c(starts_with("lat"), starts_with("lon")), ~ round(.x, 5)))

nsf_terminations_clean <- nsf_terminations_clean %>%
  rename_with(~ paste0(.x, ".nsf", recycle0 = TRUE), c("org_name", "org_state", "org_city", "lat", "lon")) %>%
  left_join(org_dict %>% select(-ends_with(".nih"), -c(lat.nsf, lon.nsf, corrected_name)) %>% distinct()) %>% 
  mutate(org_name = if_else(is.na(org_name), org_name.nsf, org_name),
         org_city = if_else(is.na(org_city), org_city.nsf, org_city),
         org_state = if_else(is.na(org_state), org_state.nsf, org_state),
         lat = if_else(is.na(lat), lat.nsf, lat),
         lon = if_else(is.na(lon), lon.nsf, lon)) %>%
  select(-ends_with(".nih"), ends_with(".nsf")) %>%
  mutate(lat = if_else(org_name == "Rutgers University Newark", 40.74054, lat),
         lon = if_else(org_name == "Rutgers University Newark", -74.17268, lon))

# organization level
terminations_org_nsf <- nsf_terminations_clean %>%
  complete(nesting(org_name, org_city, org_state, lat, lon), 
           week = seq(start_date, today(), by = "weeks"),
           fill = list(total_loss = 0, total_impacted = 0, grant_loss = 0, grants_impacted = 0)) %>%
  group_by(org_name, org_city, org_state, lat, lon, week) %>%
  summarize(across(c(total_loss, total_impacted, grant_loss, grants_impacted), ~ sum(.x))) %>%
  group_by(org_name, org_city, org_state, lat, lon) %>%
  arrange(week) %>%
  mutate(across(c(total_loss, total_impacted, grant_loss, grants_impacted), ~ cumsum(.x))) %>%
  rename(current_loss = total_loss,
         overall_loss = total_impacted,
         current_grant_loss = grant_loss,
         overall_grant_loss = grants_impacted) %>%
  left_join(states %>% rename(org_state = state)) %>%
  mutate(current_econ_loss = current_loss * nsf_econ_mult,
         current_job_loss = current_loss * nsf_job_val,
         overall_econ_loss = overall_loss * nsf_econ_mult,
         overall_job_loss = overall_loss * nsf_job_val) %>%
  select(org_name, org_city, org_state, lat, lon, starts_with(c("week", "current", "overall")))

write_csv(terminations_org_nsf, "output/terminations_org_nsf.csv")

```

```{r}
terminations_sum_nsf <- nsf_terminations %>%
  group_by(tractid, week) %>%
  summarise(week_loss = sum(total_loss),
            week_impacted = sum(total_impacted))

# tract to county commutes
terminations_sum_comm_nsf <- county_commute %>%
  rename(tractid = DESTINATION) %>%
  right_join(terminations_sum_nsf) %>%
  mutate(week_loss = week_loss * proportion,
         week_impacted = week_impacted * proportion) %>%
  group_by(ORIGIN, week) %>%
  summarize(week_loss = sum(week_loss),
            week_impacted = sum(week_impacted)) %>%
  rename(FIPS = ORIGIN) %>%
  filter(!endsWith(FIPS, "000")) %>%
  ungroup() %>%
  complete(FIPS, week = seq(start_date, today(), by = "weeks"),
           fill = list(week_loss = 0, week_impacted = 0)) %>%
  group_by(FIPS) %>%
  arrange(week) %>%
  mutate(current_loss = cumsum(week_loss),
         overall_loss = cumsum(week_impacted))

# add in state multipliers
terminations_sum_comm_nsf <- terminations_sum_comm_nsf %>%
  mutate(state_FIPS = str_sub(FIPS, 1, 2)) %>%
  left_join(states) %>%
  mutate(current_econ_loss = current_loss * nsf_econ_mult,
         current_job_loss = current_loss * nsf_job_val,
         overall_econ_loss = overall_loss * nsf_econ_mult,
         overall_job_loss = overall_loss * nsf_job_val) %>%
  select(FIPS, week, starts_with(c("current", "overall")))

# county level
write_csv(terminations_sum_comm_nsf, "output/terminations_county_nsf.csv")
```

```{r}
msa <- read.csv("data/cbsa2fipsxw_2023.csv") %>%
  select(CountyFIPS, CBSA_NAME, CBSA_FIPS) %>%
  rename(FIPS = CountyFIPS) %>%
  mutate(FIPS = str_pad(FIPS, 5, pad ="0"),
         CBSA_FIPS = str_pad(CBSA_FIPS, 5, pad ="0"))

fips_names <- read.csv("data/state_and_county_fips_master.csv") %>%
  mutate(FIPS = str_pad(FIPS, 5, pad ="0")) %>%
  select(FIPS, name)

# city level
terminations_sum_comm_nsf %>%
  left_join(msa) %>%
  left_join(fips_names) %>%
  mutate(CBSA_FIPS = ifelse(is.na(CBSA_FIPS), FIPS, CBSA_FIPS)) %>%
  mutate(CBSA_NAME = ifelse(is.na(CBSA_NAME), name, CBSA_NAME)) %>%
  group_by(CBSA_FIPS, CBSA_NAME, week) %>%
  summarise(across(ends_with("loss"), ~ sum(.x))) %>%
  write_csv("output/terminations_city_nsf.csv")
```

```{r}
# tract to district commutes
terminations_sum_cong_nsf <- cong_commute %>%
  rename(tractid = DESTINATION) %>%
  right_join(terminations_sum_nsf) %>%
  mutate(week_loss = week_loss * proportion,
         week_impacted = week_impacted * proportion) %>%
  group_by(ORIGIN, week) %>%
  summarize(week_loss = sum(week_loss),
            week_impacted = sum(week_impacted)) %>%
  rename(GEOID = ORIGIN) %>%
  filter(GEOID != "0000") %>%
  ungroup() %>%
  complete(GEOID, week = seq(start_date, today(), by = "weeks"),
           fill = list(week_loss = 0, week_impacted = 0)) %>%
  group_by(GEOID) %>%
  arrange(week) %>%
  mutate(current_loss = cumsum(week_loss),
         overall_loss = cumsum(week_impacted))

terminations_sum_cong_nsf <- terminations_sum_cong_nsf %>%
  mutate(state_FIPS = str_sub(GEOID, 1, 2)) %>%
  left_join(states) %>%
  mutate(current_econ_loss = current_loss * nsf_econ_mult,
         current_job_loss = current_loss * nsf_job_val,
         overall_econ_loss = overall_loss * nsf_econ_mult,
         overall_job_loss = overall_loss * nsf_job_val) %>%
  select(GEOID, state, week, starts_with(c("current", "overall")))

# district level
write_csv(terminations_sum_cong_nsf %>% select(-state), "output/terminations_district_nsf.csv")

# state level
terminations_sum_cong_nsf %>%
  group_by(state, week) %>%
  summarise(across(ends_with("loss"), ~ sum(.x))) %>%
  write_csv("output/terminations_state_nsf.csv")
```

```{r website values}
terminations_sum_cong_nsf %>%
  filter(week == max(week)) %>%
  ungroup() %>%
  summarize(raw_loss_ever = sum(overall_loss),
            econ_loss_ever = sum(overall_econ_loss),
            job_loss_ever = sum(overall_job_loss),
            raw_loss_current = sum(current_loss),
            econ_loss_current = sum(current_econ_loss),
            job_loss_current = sum(current_job_loss))
```

```{r check values}
county_tot <- terminations_sum_comm_nsf %>%
  filter(week == max(week))
cong_tot <- terminations_sum_cong_nsf %>%
  filter(week == max(week))

sum(nsf_terminations$total_loss)
sum(county_tot$current_loss)
sum(cong_tot$current_loss)

sum(nsf_terminations$total_impacted)
sum(county_tot$overall_loss)
sum(cong_tot$overall_loss)
```

