---
title: "NSF-budget-cuts-v25"
output: html_document
date: "2025-08-22"
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require('rstudioapi')) BiocManager::install("rstudioapi");library(rstudioapi)

# change working directory to folder with script
setwd(dirname(rstudioapi::getSourceEditorContext()$path)) 

library(tidyverse)
library(readxl)
library(sf)
library(data.table)
library(magrittr)

options(scipen=999)
```

```{r combine-files, eval=FALSE}
library(jsonlite)
library(purrr)
library(dplyr)
library(readr)

# get path for NSF grants
json_folder <- "NSF_Grants"
json_files <- list.files(json_folder, pattern = "\\.json$", full.names = TRUE)

extract_fields <- function(grant) {
  data.frame(fund_oblg_fiscal_yr = grant$oblg_fy$fund_oblg_fiscal_yr,
             fund_oblg_amt = grant$oblg_fy$fund_oblg_amt) %>%
    mutate(awd_id = grant$awd_id %||% NA,
           agcy_id = grant$agcy_id %||% NA,
           tran_type = grant$tran_type %||% NA,
           awd_inst_txt = grant$awd_istr_txt %||% NA,
           cfda_num = grant$cfda_num %||% NA,
           awd_eff_date = grant$awd_eff_date %||% NA,
           awd_exp_date = grant$awd_exp_date %||% NA,
           tot_intn_awd_amt = grant$tot_intn_awd_amt %||% NA,
           awd_amount = grant$awd_amount %||% NA,
           awd_min_amd_letter_date = grant$awd_min_amd_letter_date %||% NA,
           awd_max_amd_letter_date = grant$awd_max_amd_letter_date %||% NA,
           dir_abbr = grant$dir_abbr %||% NA,
           div_abbr = grant$div_abbr %||% NA,
           inst_name = grant$inst$inst_name %||% NA,
           inst_street_address = grant$inst$inst_street_address %||% NA,
           inst_city_name = grant$inst$inst_city_name %||% NA,
           inst_state_name = grant$inst$inst_state_name %||% NA,
           inst_zip  = grant$inst$inst_zip_code %||% NA,
           awd_instr = grant$awd_istr_txt %||% NA)
}


# Apply extraction to each record
all_data <- map_dfr(json_files, function(file) {
  fromJSON(file) %>% extract_fields()
})

library(data.table)

fwrite(all_data, "nsf_grants.csv")
```


```{r clean-grants}
nsf_grants <- read.csv("nsf_data/nsf_grants.csv")

#directorates to include
dir_incl <- c("BIO", "CSE", "EDU", "ENG", "GEO", "MPS", "SBE", "TIP")

# divisions within office of director to include
div_incl <- c("OIA", "OISE", "OPP")

# helper column to put listed account categories together (O/D divisions are split out) and OPP is split out of GEOSW
nsf_grants %<>% mutate(account_name = ifelse(dir_abbr == "O/D", div_abbr, dir_abbr)) %>%
  mutate(account_name = ifelse(div_abbr=="OPP", "OPP", account_name)) %>%
  filter(account_name %in% c(dir_incl, div_incl)) 
```


```{r budget-cuts}
# https://www.usinflationcalculator.com/ 2020-2027 dollars inflation adjusted to 2026 using: https://www.usinflationcalculator.com/ and assumption of 2% inflation from 2026 to 2027 
inf_adj <- c(1.26, 1.21, 1.12, 1.07, 1.04, 1.02, 1, .98)
inf_by_year <- tibble(inf = inf_adj, fund_oblg_fiscal_yr = c(2020:2027))
# df of historic funding in FY2020-2025, proposed for FY2027 via 
# appropriation tabs (FY2020-FY2024) https://www.nsf.gov/about/budget/all and table (FY2025 and FY2027):  # https://nsf-gov-resources.nsf.gov/files/FY-2027-NSF-Budget-Request-to-Congress.pdf
# unit is dollars in millions
budg_tab <- read.csv("data/nsf_budg_table.csv") %>%
            filter(!is.na(X)) %>%
            mutate(across(X2020_budg:X2027_budg, ~as.numeric(.x)))

budg_tab %<>%
  rowwise() %>%
  mutate(across(X2020_budg:X2027_budg)*inf_adj) %>%
  mutate(past_mean = mean(c_across(X2020_budg:X2024_budg), na.rm = TRUE)) %>%
  mutate(prop_cut = 1 - X2027_budg/past_mean) %>%
  ungroup() %>%
  rename(account_name = X) %>%
  pivot_longer(
    cols = starts_with("X"),
    names_to = "fund_oblg_fiscal_yr",
    values_to = "budg_sum",
    names_pattern = "X(\\d+)_budg"
  ) %>%
  mutate(fund_oblg_fiscal_yr = as.numeric(fund_oblg_fiscal_yr),
         budg_sum = budg_sum*10^6) 

# calculate losses for each grant
nsf_grants %<>% 
  left_join(inf_by_year) %>%
  filter(!is.na(inf)) %>%
  mutate(adj_fund = inf * fund_oblg_amt) %>%
  filter(fund_oblg_fiscal_yr >=2020 & fund_oblg_fiscal_yr <= 2024) %>%
  filter(! (account_name=="TIP" & fund_oblg_fiscal_yr < 2022)) %>%
  left_join(budg_tab) %>%
  filter(!is.na(budg_sum)) %>%
  group_by(account_name, fund_oblg_fiscal_yr) %>%
  mutate(oblg_sum = sum(adj_fund, na.rm=TRUE)) %>%
  ungroup() %>%
  mutate(oblg_mult = budg_sum / oblg_sum) %>%
  mutate(adj_fund = adj_fund * oblg_mult) %>% 
  mutate(cut_amt = prop_cut * adj_fund)

```


```{r Get FIPS Codes}

geo_dict <- read.csv("nsf_data/NSF_addresses_US_tract_county_cong119.csv") %>%
  distinct() %>%
  mutate(FIPS = str_pad(CountyFIPS_str, 5, pad = "0"),
         GEOID = str_pad(CongFIPS, 4, pad="0"),
         tractid = str_pad(TractFIPS_Str, 11, pad="0"),
         inst_street_address = inst_stree) %>%
  filter(inst_state %in% c(state.name, "District of Columbia")) %>%
  select(tractid, inst_street_address, inst_name) %>%
  distinct()

nsf_grants_inst <- nsf_grants %>%
  left_join(geo_dict) %>%
  group_by(tractid, account_name, inst_name, fund_oblg_fiscal_yr) %>%
  summarise(budg_loss = sum(cut_amt, na.rm=TRUE),
            budg_tot = sum(adj_fund, na.rm=TRUE)) 

nsf_grants %<>% left_join(geo_dict) %>%
  group_by(tractid, account_name, fund_oblg_fiscal_yr) %>%
  summarise(budg_loss = sum(cut_amt, na.rm=TRUE),
            budg_tot = sum(adj_fund, na.rm=TRUE)) 

# dictionary to map fips codes to state names
NSF_state_dict <- read.csv("data/state_and_county_fips_master.csv") %>%
  mutate(FIPS = str_pad(FIPS, 5, pad = "0")) %>%
  filter(!endsWith(FIPS, "000")) 

# append state FIPS codes
NSF_state_dict <- tibble(
  state_name = c(state.name, "District of Columbia"),
  state = c(state.abb, "DC")) %>%
  right_join(NSF_state_dict) %>%
  mutate(state_FIPS = str_sub(FIPS, 1, 2)) %>%
  arrange(state) 

```

```{r Commuter Weighting}
# commute is a dataframe derived from 2016 Census data with the following columns
# ORIGIN: is the FIPS code for the county of residence
# proportion: is the proportion of people working in a given DESTINATION who live in a specific ORIGIN

# IMPORTANT: some FIPS codes have leading zeros
commute <- fread("data/county_commute_NIH.csv") %>%
  select(DESTINATION, DESTINATION_total_workers, Commuters, ORIGIN, proportion) %>% 
  mutate(DESTINATION = str_pad(DESTINATION, 11, pad = "0"),
         ORIGIN = str_pad(ORIGIN, 5, pad = "0"))

```

```{r County Calculations}

#summarize NIH data by FIPS code
NSF_budget_cuts_tract <- nsf_grants %>%
  ungroup() %>%
  complete(account_name, tractid, fund_oblg_fiscal_yr, fill=list(budg_loss=0)) %>%
  filter(! (account_name=="TIP" & fund_oblg_fiscal_yr < 2022)) %>%
  group_by(tractid, account_name) %>%
  summarise(budg_loss = mean(budg_loss, na.rm=TRUE))

#combine commuter data with NSF data
county_commute_NSF <- merge(commute, NSF_budget_cuts_tract, by.x = "DESTINATION", by.y = "tractid", all.x = TRUE, allow.cartesian=TRUE) %>%
  filter(!is.na(account_name)) %>%
  mutate_all(funs(replace(., is.na(.), 0))) %>%
  mutate(budg_loss = budg_loss * proportion) %>%
  rename(FIPS = ORIGIN) %>%
  group_by(FIPS, account_name) %>%
  summarize(budg_loss = sum(budg_loss, na.rm=TRUE)) %>%
  ungroup() %>%
  pivot_wider(names_from = account_name, 
              names_glue = "budg_{account_name}_cuts",
              values_from = budg_loss) %>%
  rowwise() %>%
  mutate(budg_NSF_cuts = sum(c_across(starts_with("budg")), na.rm = TRUE)) %>%
  ungroup() %>%
  mutate_all(funs(replace(., is.na(.), 0)))  %>%
  right_join(NSF_state_dict) %>%
  mutate(across(starts_with("budg"), ~ .x * 2.64, .names = "econ_{.col}")) %>%
  mutate(across(starts_with("budg"), ~ .x / 72000, .names = "jobs_{.col}"))

print(nrow(county_commute_NSF))

write.csv(county_commute_NSF, "output/NSF_budget27_county.csv", row.names=FALSE)

```

```{r city-level}
msa <- read.csv("data/cbsa2fipsxw_2023.csv") %>%
  select(CountyFIPS, CBSA_NAME, CBSA_FIPS) %>%
  rename(FIPS = CountyFIPS) %>%
  mutate(FIPS = str_pad(FIPS, 5, pad ="0"),
         CBSA_FIPS = str_pad(CBSA_FIPS, 5, pad ="0"))

city_commute_NSF_sum <- county_commute_NSF %>% 
                        left_join(msa) %>%
                        mutate(CBSA_FIPS = ifelse(is.na(CBSA_FIPS), FIPS, CBSA_FIPS),
                               CBSA_NAME = ifelse(is.na(CBSA_NAME), paste(name, state, sep = ", "), CBSA_NAME)) %>%
                        select(CBSA_FIPS, CBSA_NAME, state_name, state, ends_with("cuts")) %>%
  group_by(CBSA_FIPS, CBSA_NAME) %>%
  summarize(across(ends_with("cuts"), sum, na.rm = TRUE))

write.csv(city_commute_NSF_sum, "output/NSF_budget27_city.csv", row.names=FALSE)
```

# Congressional Districts

```{r Prep District Commuter Flows}
cong_commute <- fread("https://osf.io/m5kb6/download") %>%
  mutate(Cong_DESTINATION = str_pad(w_tract, 11, pad = "0"),
         Cong_ORIGIN = str_pad(h_cd119, 4, pad = "0")) %>%
  rename(commuters = commutes) %>%
  filter(!is.na(Cong_ORIGIN))

cong_info <- read.csv("./data/us_representatives_119th_congress.csv") %>%
  mutate(GEOID = str_pad(GEOID, 4, pad = "0")) %>%
  select(GEOID, STATE_NAME, NAME, PARTY) %>%
  rename(state = STATE_NAME,
         pol_party = PARTY,
         rep_name = NAME)

#get total workers per cong district
cong_commute_sum <- cong_commute %>%
  group_by(Cong_DESTINATION) %>%
  summarise(total_workers = sum(commuters, na.rm=TRUE))

#merge in total workers
cong_commute <- left_join(cong_commute, cong_commute_sum) %>%
  select(Cong_DESTINATION, Cong_ORIGIN, commuters, total_workers) %>%
  rename(DESTINATION = Cong_DESTINATION,
         ORIGIN = Cong_ORIGIN) 

#calculate proportion of workers who work in district X who live in district Y
cong_commute$proportion <- cong_commute$commuters / cong_commute$total_workers
```


```{r Merge Cong Data}
#combine commuter data with NIH data
cong_commute_NSF <- merge(cong_commute, NSF_budget_cuts_tract, by.x = "DESTINATION", by.y = "tractid", all = TRUE, allow.cartesian=TRUE) %>%
  filter(!is.na(account_name)) %>%
  mutate_all(funs(replace(., is.na(.), 0))) %>%
  mutate(budg_loss = budg_loss * proportion) %>%
  rename(GEOID = ORIGIN) %>%
  group_by(GEOID, account_name) %>%
  summarize(budg_loss = sum(budg_loss, na.rm=TRUE)) %>%
  ungroup() %>%
    pivot_wider(names_from = account_name, 
              names_glue = "budg_{account_name}_cuts",
              values_from = budg_loss) %>%
  rowwise() %>%
  mutate(budg_NSF_cuts = sum(c_across(starts_with("budg")), na.rm = TRUE)) %>%
  ungroup() %>%
  mutate_all(funs(replace(., is.na(.), 0)))  %>%
  left_join(cong_info %>% rename(state_name=state)) %>%
  left_join(NSF_state_dict %>% 
              select(state, state_name, state_FIPS) %>% 
              distinct()) %>%
  mutate(across(starts_with("budg"), ~ .x * 2.64, .names = "econ_{.col}")) %>%
  mutate(across(starts_with("budg"), ~ .x / 72000, .names = "jobs_{.col}")) %>%
  filter(GEOID != "0")


print(nrow(cong_commute_NSF))

write.csv(cong_commute_NSF, "output/NSF_budget27_cong.csv", row.names=F)
```

```{r cong-inst}
NSF_inst_tract <- nsf_grants_inst %>%
  ungroup() %>%
  filter(! (account_name=="TIP" & fund_oblg_fiscal_yr < 2022)) %>%
  group_by(tractid, inst_name, account_name) %>%
  summarise(budg_loss = sum(budg_loss, na.rm=TRUE)/ifelse(account_name=="TIP", 3, 5)) %>%
  distinct()


#combine commuter data with NIH data
cong_commute_NSF_inst <- merge(cong_commute, NSF_inst_tract, by.x = "DESTINATION", by.y = "tractid", all = TRUE, allow.cartesian=TRUE) %>%
  filter(!is.na(account_name)) %>%
  mutate_all(funs(replace(., is.na(.), 0))) %>%
  mutate(budg_loss = budg_loss * proportion) %>%
  rename(GEOID = ORIGIN) %>%
  group_by(GEOID, inst_name, account_name) %>%
  summarize(budg_loss = sum(budg_loss, na.rm=TRUE)) %>%
  ungroup() %>%
    pivot_wider(names_from = account_name, 
              names_glue = "budg_{account_name}_cuts",
              values_from = budg_loss) %>%
  rowwise() %>%
  mutate(budg_NSF_cuts = sum(c_across(starts_with("budg")), na.rm = TRUE)) %>%
  ungroup() %>%
  mutate_all(funs(replace(., is.na(.), 0)))  %>%
  left_join(cong_info %>% rename(state_name=state)) %>%
  left_join(NSF_state_dict %>% 
              select(state, state_name, state_FIPS) %>% 
              distinct()) %>%
  mutate(across(starts_with("budg"), ~ .x * 2.64, .names = "econ_{.col}")) %>%
  mutate(across(starts_with("budg"), ~ .x / 72000, .names = "jobs_{.col}")) %>%
  filter(GEOID != "0") %>%
  group_by(GEOID) %>%
  slice_max(budg_NSF_cuts, n=5)


print(nrow(cong_commute_NSF_inst))

write.csv(cong_commute_NSF_inst, "output/NSF_budget27_cong_top5inst.csv", row.names=F)


```

```{r state summaries}
cong_commute_NSF %>%
  group_by(state, state_name) %>%
  summarise(across(ends_with(c("cuts")), ~ sum(.x, na.rm = TRUE))) -> state_cong

print(nrow(state_cong))

write.csv(state_cong, file="output/NSF_budget27_state.csv", row.names=FALSE)

```
```{r state inst}
NSF_inst_tract <- nsf_grants_inst %>%
  ungroup() %>%
  filter(! (account_name=="TIP" & fund_oblg_fiscal_yr < 2022)) %>%
  group_by(tractid, inst_name, account_name) %>%
  summarise(budg_loss = sum(budg_loss, na.rm=TRUE)/ifelse(account_name=="TIP", 3, 5)) %>%
  distinct()


#combine commuter data with NIH data
state_commute_NSF_inst <- merge(cong_commute, NSF_inst_tract, by.x = "DESTINATION", by.y = "tractid", all = TRUE, allow.cartesian=TRUE) %>%
  filter(!is.na(account_name)) %>%
  mutate_all(funs(replace(., is.na(.), 0))) %>%
  mutate(budg_loss = budg_loss * proportion) %>%
  rename(GEOID = ORIGIN) %>%
  group_by(GEOID, inst_name, account_name) %>%
  summarize(budg_loss = sum(budg_loss, na.rm=TRUE)) %>%
  ungroup() %>%
    pivot_wider(names_from = account_name, 
              names_glue = "budg_{account_name}_cuts",
              values_from = budg_loss) %>%
  rowwise() %>%
  mutate(budg_NSF_cuts = sum(c_across(starts_with("budg")), na.rm = TRUE)) %>%
  ungroup() %>%
  mutate_all(funs(replace(., is.na(.), 0)))  %>%
  left_join(cong_info %>% rename(state_name=state)) %>%
  left_join(NSF_state_dict %>% 
              select(state, state_name, state_FIPS) %>% 
              distinct()) %>%
  mutate(across(starts_with("budg"), ~ .x * 2.64, .names = "econ_{.col}")) %>%
  mutate(across(starts_with("budg"), ~ .x / 72000, .names = "jobs_{.col}")) %>%
  filter(GEOID != "0") %>%
  group_by(state_name) %>%
  slice_max(budg_NSF_cuts, n=5)


write.csv(state_commute_NSF_inst, "output/NSF_budget27_state_top5inst.csv", row.names=F)
```

```{r Get Stats Used in Report}
# note that these sums are slightly greater than summing across NSF_budget_cuts_tract because funding to international institutions/territories is ignored
budg_tab %>% select(past_mean) %>% distinct() %>% summarize(tot_hist_budg = sum(past_mean, na.rm=TRUE))
NSF_budg_state <- read.csv("output/NSF_budget27_state.csv")
cong_commute_NSF <- read.csv("output/NSF_budget27_cong.csv")

sum(NSF_budget_cuts_tract$budg_loss, na.rm=TRUE)
sum(NSF_budget_cuts_tract$budg_loss*2.64, na.rm=TRUE)
sum(NSF_budget_cuts_tract$budg_loss/72000, na.rm=TRUE)

filter(NSF_budg_state, econ_budg_NSF_cuts>10^8)
cong_commute_NSF %>% filter(econ_budg_NSF_cuts > 10^7)
cong_commute_NSF %>% filter(econ_budg_NSF_cuts > 0)

budg_tab %>% select(account_name, prop_cut) %>% distinct()
budg_tab %>% filter(account_name == "EDU" & fund_oblg_fiscal_yr==2027)
budg_tab %>% filter(account_name == "SBE" & fund_oblg_fiscal_yr==2027)

```
